import React, { useEffect } from "react";
import Head from 'next/head'
import { Banner } from '@/components/Banner'
import { WhyChooseUs } from '@/components/WhyChooseUs'
import { ExploreMore } from '@/components/ExploreMore'
import { KeyFeature } from '@/components/KeyFeature'
import { Tabs } from '@/components/Tabs'
import { Pricing } from '@/components/Pricing'
import { CallToAction } from '@/components/CallToAction'
import { Testimonials } from '@/components/Testimonials'
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";


gsap.registerPlugin(ScrollTrigger);

export default function Home() {

  useEffect(() => {
    // Set up ScrollTrigger animations for each section
    const sections = gsap.utils.toArray(".section");

    sections.forEach((section, index) => {
      const bgColor = section.dataset.bgcolor;

      gsap.set(section, { backgroundColor: bgColor });

      gsap.from(section, {
        opacity: 0,
        duration: 1,
        ease: "power4.out",
        scrollTrigger: {
          trigger: section,
          start: "top center",
          end: "bottom center",
          scrub: true,
          toggleActions: "play none none none", // This ensures the animation plays when the section enters the viewport and is removed when it leaves
        },
      });

      // Ensure that the last section doesn't trigger the background change
      if (index !== sections.length - 1) {
        gsap.to(section, {
          opacity: 0,
          duration: 1,
          ease: "power4.out",
          scrollTrigger: {
            trigger: sections[index + 1], // Use the next section as the trigger
            start: "top center",
            end: "top center",
            scrub: true,
            toggleActions: "none none none none", // This disables the animation when the next section is visible
          },
        });
      }
    });
  }, []);



  return (
    <>
      <Head>
        <title>Logo Design Valley</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner 
        Heading={
          <>
          Award Winning Professional Logo <br/> Design Company in the US
          </>
        }
        FormHeading = "Insanely professional logo maker services poured with passion and proficiency"
        BgImageURL = "./assets/images/bannerbg.webp"
        bgColor="red"
      />
      <div className="section" data-bgcolor="#ff0000">
      <WhyChooseUs />
      </div>
      <div className="section" data-bgcolor="#00ff00">
      <ExploreMore
        Heading="Folks think we're rad. We're rated 4.8/5 from 100+ customer reviews."
        BtnLink="#"
        BtnText="Explore More Here"
      />
      </div>
      <div className="section" data-bgcolor="#0000ff">
      <KeyFeature/>
      </div>
      <div className="section" data-bgcolor="#ff0000">
      <Tabs />
      </div>
      <div className="section" data-bgcolor="#00ff00">
      <Pricing 
        ComboPack_SubHeading = "All In One"
        ComboPack_Heading = "Combo Package"
        ComboPack_Description = "Ultimate Value for Start-ups and Brand(s)"
      />
      </div>
      <div className="section" data-bgcolor="#0000ff">
      <CallToAction 
         Heading = "Get Your Project Started Today"
         Para = "At our company, we value communication and understand the importance of open dialogue between our team and our clients. That's why we encourage you to talk to us – whether it's to discuss a new project, ask a question, or provide feedback on our services."
      />
      </div>
      <div className="section" data-bgcolor="#ff0000">
      <Testimonials 
        Heading = "Testimonials"
      />
      </div>
      
    </>
  )
}
